/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = string;
export type GameMode = { 'far' : null } |
  { 'near' : null };
export interface MatchProgress {
  'lastRoundScores' : [] | [ScoringResult],
  'currentRound' : bigint,
  'cumulativeScores' : Array<Score>,
  'isActive' : boolean,
  'currentLetter' : [] | [string],
  'totalRounds' : bigint,
  'usedLetters' : Array<string>,
}
export interface MonthlyScoreView {
  'userId' : UserId,
  'wins' : bigint,
  'lastUpdated' : Time,
  'rounds' : bigint,
  'points' : bigint,
}
export type RoomId = bigint;
export interface RoomView {
  'id' : RoomId,
  'categories' : Array<Category>,
  'active' : boolean,
  'host' : UserId,
  'mode' : GameMode,
  'players' : Array<UserId>,
}
export interface RoundPayload {
  'isActive' : boolean,
  'totalRounds' : bigint,
  'letter' : string,
  'roundNumber' : bigint,
}
export interface Score { 'player' : UserId, 'points' : bigint }
export interface ScoringResult {
  'maxPoints' : bigint,
  'valid' : bigint,
  'scores' : Array<Score>,
  'empty' : bigint,
  'repeats' : bigint,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Submission = string;
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserId = Principal;
export interface UserProfileView {
  'id' : UserId,
  'name' : string,
  'banned' : boolean,
  'entitlements' : Array<string>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addWord' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'banUser' : ActorMethod<[UserId], undefined>,
  'banWord' : ActorMethod<[string], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createRoom' : ActorMethod<[GameMode, Array<Category>], RoomId>,
  'getAllowedGameModes' : ActorMethod<[], Array<GameMode>>,
  'getAvailableRooms' : ActorMethod<[], Array<RoomView>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfileView]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentMatchState' : ActorMethod<[RoomId], MatchProgress>,
  'getCurrentMonthLeaderboard' : ActorMethod<[], Array<MonthlyScoreView>>,
  'getCurrentTop1' : ActorMethod<[], [] | [MonthlyScoreView]>,
  'getDictionaryEntry' : ActorMethod<[string], [] | [boolean]>,
  'getMetrics' : ActorMethod<
    [],
    {
      'bannedUsers' : bigint,
      'activeRooms' : bigint,
      'totalUsers' : bigint,
      'totalRooms' : bigint,
    }
  >,
  'getMonthLeaderboard' : ActorMethod<[string], Array<MonthlyScoreView>>,
  'getMyMonthlyScore' : ActorMethod<[string], [] | [MonthlyScoreView]>,
  'getMyRooms' : ActorMethod<[], Array<RoomView>>,
  'getRoom' : ActorMethod<[RoomId], RoomView>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfileView]>,
  'getValidationResults' : ActorMethod<
    [RoomId],
    Array<
      {
        'submitter' : UserId,
        'word' : string,
        'category' : Category,
        'isValid' : boolean,
      }
    >
  >,
  'grantEntitlement' : ActorMethod<[UserId, string], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'joinMatchmaking' : ActorMethod<[], undefined>,
  'joinRoom' : ActorMethod<[RoomId], undefined>,
  'leaveMatchmaking' : ActorMethod<[], undefined>,
  'leaveRoom' : ActorMethod<[RoomId], undefined>,
  'purchaseProduct' : ActorMethod<[string], string>,
  'register' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfileView], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'startGame' : ActorMethod<[RoomId], undefined>,
  'startRound' : ActorMethod<[RoomId], RoundPayload>,
  'stopCurrentRound' : ActorMethod<[RoomId], string>,
  'submitWord' : ActorMethod<[RoomId, Category, Submission], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'unbanUser' : ActorMethod<[UserId], undefined>,
  'updateMonthlyScore' : ActorMethod<[UserId, bigint, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];