/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserId = IDL.Principal;
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const GameMode = IDL.Variant({ 'far' : IDL.Null, 'near' : IDL.Null });
export const Category = IDL.Text;
export const RoomId = IDL.Nat;
export const RoomView = IDL.Record({
  'id' : RoomId,
  'categories' : IDL.Vec(Category),
  'active' : IDL.Bool,
  'host' : UserId,
  'mode' : GameMode,
  'players' : IDL.Vec(UserId),
});
export const UserProfileView = IDL.Record({
  'id' : UserId,
  'name' : IDL.Text,
  'banned' : IDL.Bool,
  'entitlements' : IDL.Vec(IDL.Text),
});
export const Score = IDL.Record({ 'player' : UserId, 'points' : IDL.Nat });
export const ScoringResult = IDL.Record({
  'maxPoints' : IDL.Nat,
  'valid' : IDL.Nat,
  'scores' : IDL.Vec(Score),
  'empty' : IDL.Nat,
  'repeats' : IDL.Nat,
});
export const MatchProgress = IDL.Record({
  'lastRoundScores' : IDL.Opt(ScoringResult),
  'currentRound' : IDL.Nat,
  'cumulativeScores' : IDL.Vec(Score),
  'isActive' : IDL.Bool,
  'currentLetter' : IDL.Opt(IDL.Text),
  'totalRounds' : IDL.Nat,
  'usedLetters' : IDL.Vec(IDL.Text),
});
export const Time = IDL.Int;
export const MonthlyScoreView = IDL.Record({
  'userId' : UserId,
  'wins' : IDL.Nat,
  'lastUpdated' : Time,
  'rounds' : IDL.Nat,
  'points' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const RoundPayload = IDL.Record({
  'isActive' : IDL.Bool,
  'totalRounds' : IDL.Nat,
  'letter' : IDL.Text,
  'roundNumber' : IDL.Nat,
});
export const Submission = IDL.Text;
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addWord' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'banUser' : IDL.Func([UserId], [], []),
  'banWord' : IDL.Func([IDL.Text], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createRoom' : IDL.Func([GameMode, IDL.Vec(Category)], [RoomId], []),
  'getAllowedGameModes' : IDL.Func([], [IDL.Vec(GameMode)], ['query']),
  'getAvailableRooms' : IDL.Func([], [IDL.Vec(RoomView)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfileView)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentMatchState' : IDL.Func([RoomId], [MatchProgress], ['query']),
  'getCurrentMonthLeaderboard' : IDL.Func(
      [],
      [IDL.Vec(MonthlyScoreView)],
      ['query'],
    ),
  'getCurrentTop1' : IDL.Func([], [IDL.Opt(MonthlyScoreView)], ['query']),
  'getDictionaryEntry' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Bool)], ['query']),
  'getMetrics' : IDL.Func(
      [],
      [
        IDL.Record({
          'bannedUsers' : IDL.Nat,
          'activeRooms' : IDL.Nat,
          'totalUsers' : IDL.Nat,
          'totalRooms' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getMonthLeaderboard' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MonthlyScoreView)],
      ['query'],
    ),
  'getMyMonthlyScore' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(MonthlyScoreView)],
      ['query'],
    ),
  'getMyRooms' : IDL.Func([], [IDL.Vec(RoomView)], ['query']),
  'getRoom' : IDL.Func([RoomId], [RoomView], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfileView)],
      ['query'],
    ),
  'getValidationResults' : IDL.Func(
      [RoomId],
      [
        IDL.Vec(
          IDL.Record({
            'submitter' : UserId,
            'word' : IDL.Text,
            'category' : Category,
            'isValid' : IDL.Bool,
          })
        ),
      ],
      ['query'],
    ),
  'grantEntitlement' : IDL.Func([UserId, IDL.Text], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'joinMatchmaking' : IDL.Func([], [], []),
  'joinRoom' : IDL.Func([RoomId], [], []),
  'leaveMatchmaking' : IDL.Func([], [], []),
  'leaveRoom' : IDL.Func([RoomId], [], []),
  'purchaseProduct' : IDL.Func([IDL.Text], [IDL.Text], []),
  'register' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfileView], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'startGame' : IDL.Func([RoomId], [], []),
  'startRound' : IDL.Func([RoomId], [RoundPayload], []),
  'stopCurrentRound' : IDL.Func([RoomId], [IDL.Text], []),
  'submitWord' : IDL.Func([RoomId, Category, Submission], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'unbanUser' : IDL.Func([UserId], [], []),
  'updateMonthlyScore' : IDL.Func([UserId, IDL.Nat, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const GameMode = IDL.Variant({ 'far' : IDL.Null, 'near' : IDL.Null });
  const Category = IDL.Text;
  const RoomId = IDL.Nat;
  const RoomView = IDL.Record({
    'id' : RoomId,
    'categories' : IDL.Vec(Category),
    'active' : IDL.Bool,
    'host' : UserId,
    'mode' : GameMode,
    'players' : IDL.Vec(UserId),
  });
  const UserProfileView = IDL.Record({
    'id' : UserId,
    'name' : IDL.Text,
    'banned' : IDL.Bool,
    'entitlements' : IDL.Vec(IDL.Text),
  });
  const Score = IDL.Record({ 'player' : UserId, 'points' : IDL.Nat });
  const ScoringResult = IDL.Record({
    'maxPoints' : IDL.Nat,
    'valid' : IDL.Nat,
    'scores' : IDL.Vec(Score),
    'empty' : IDL.Nat,
    'repeats' : IDL.Nat,
  });
  const MatchProgress = IDL.Record({
    'lastRoundScores' : IDL.Opt(ScoringResult),
    'currentRound' : IDL.Nat,
    'cumulativeScores' : IDL.Vec(Score),
    'isActive' : IDL.Bool,
    'currentLetter' : IDL.Opt(IDL.Text),
    'totalRounds' : IDL.Nat,
    'usedLetters' : IDL.Vec(IDL.Text),
  });
  const Time = IDL.Int;
  const MonthlyScoreView = IDL.Record({
    'userId' : UserId,
    'wins' : IDL.Nat,
    'lastUpdated' : Time,
    'rounds' : IDL.Nat,
    'points' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const RoundPayload = IDL.Record({
    'isActive' : IDL.Bool,
    'totalRounds' : IDL.Nat,
    'letter' : IDL.Text,
    'roundNumber' : IDL.Nat,
  });
  const Submission = IDL.Text;
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addWord' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'banUser' : IDL.Func([UserId], [], []),
    'banWord' : IDL.Func([IDL.Text], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createRoom' : IDL.Func([GameMode, IDL.Vec(Category)], [RoomId], []),
    'getAllowedGameModes' : IDL.Func([], [IDL.Vec(GameMode)], ['query']),
    'getAvailableRooms' : IDL.Func([], [IDL.Vec(RoomView)], ['query']),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(UserProfileView)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentMatchState' : IDL.Func([RoomId], [MatchProgress], ['query']),
    'getCurrentMonthLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(MonthlyScoreView)],
        ['query'],
      ),
    'getCurrentTop1' : IDL.Func([], [IDL.Opt(MonthlyScoreView)], ['query']),
    'getDictionaryEntry' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Bool)], ['query']),
    'getMetrics' : IDL.Func(
        [],
        [
          IDL.Record({
            'bannedUsers' : IDL.Nat,
            'activeRooms' : IDL.Nat,
            'totalUsers' : IDL.Nat,
            'totalRooms' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getMonthLeaderboard' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MonthlyScoreView)],
        ['query'],
      ),
    'getMyMonthlyScore' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(MonthlyScoreView)],
        ['query'],
      ),
    'getMyRooms' : IDL.Func([], [IDL.Vec(RoomView)], ['query']),
    'getRoom' : IDL.Func([RoomId], [RoomView], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfileView)],
        ['query'],
      ),
    'getValidationResults' : IDL.Func(
        [RoomId],
        [
          IDL.Vec(
            IDL.Record({
              'submitter' : UserId,
              'word' : IDL.Text,
              'category' : Category,
              'isValid' : IDL.Bool,
            })
          ),
        ],
        ['query'],
      ),
    'grantEntitlement' : IDL.Func([UserId, IDL.Text], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'joinMatchmaking' : IDL.Func([], [], []),
    'joinRoom' : IDL.Func([RoomId], [], []),
    'leaveMatchmaking' : IDL.Func([], [], []),
    'leaveRoom' : IDL.Func([RoomId], [], []),
    'purchaseProduct' : IDL.Func([IDL.Text], [IDL.Text], []),
    'register' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfileView], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'startGame' : IDL.Func([RoomId], [], []),
    'startRound' : IDL.Func([RoomId], [RoundPayload], []),
    'stopCurrentRound' : IDL.Func([RoomId], [IDL.Text], []),
    'submitWord' : IDL.Func([RoomId, Category, Submission], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'unbanUser' : IDL.Func([UserId], [], []),
    'updateMonthlyScore' : IDL.Func([UserId, IDL.Nat, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };