export const COPY = {
  splash: {
    title: '¡STOP Venezolano!',
    subtitle: 'El juego de palabras más chévere',
    cta: 'Comenzar a Jugar',
    logoAlt: 'Logo STOP Venezolano',
  },
  mainMenu: {
    title: '¡STOP Venezolano!',
    subtitle: 'Elige tu modo de juego',
    near: 'Jugar Cerca',
    nearDesc: 'Crea o únete a una sala privada',
    far: 'Jugar en Línea',
    farDesc: 'Juega con personas de todo el mundo',
    store: 'Tienda',
    storeDesc: 'Paquetes premium y personalizaciones',
    admin: 'Panel de Admin',
    adminDesc: 'Administrar configuración del juego',
    welcomeBack: 'Bienvenido de vuelta',
    playNearby: 'Jugar Cerca',
    playOnline: 'Jugar en Línea',
    visitStore: 'Visitar Tienda',
    adminPanel: 'Panel Admin',
  },
  nearDialog: {
    title: 'Jugar Cerca',
    createRoom: 'Crear Sala',
    joinRoom: 'Unirse a Sala',
    createDesc: 'Crea una sala privada y comparte el código con tus panas.',
    createButton: 'Crear Sala',
    creating: 'Creando...',
    roomCodeLabel: 'Código de Sala',
    roomCodePlaceholder: 'Ingresa el código de sala',
    joinButton: 'Unirse a Sala',
    joining: 'Uniéndose...',
    enterRoomCode: 'Por favor ingresa un código de sala',
  },
  lobby: {
    title: 'Sala de Juego',
    waitingForHost: 'Esperando que el anfitrión inicie...',
    waitingForPlayers: 'Esperando más jugadores...',
    players: 'Jugadores',
    roomCode: 'Código de Sala',
    startGame: 'Iniciar Juego',
    leave: 'Salir de la Sala',
    host: 'Anfitrión',
    player: 'Jugador',
    roomCodeCopied: '¡Código de sala copiado!',
    loading: 'Cargando sala...',
    roomNotFound: 'Sala no encontrada',
    backToMenu: 'Volver al Menú',
    inviteFriends: 'Invitar Amigos',
    shareVia: 'Compartir por',
    shareMessage: '¡Únete a mi partida de STOP Venezolano! Código de sala: {code}. Link: {link}',
    shareSuccess: '¡Invitación compartida!',
    shareError: 'No se pudo compartir',
    copyLink: 'Copiar Link',
    linkCopied: '¡Link copiado!',
    roomFull: 'La sala está llena (máximo 8 jugadores)',
    matchmakingFull: 'No hay partidas disponibles. Intenta de nuevo más tarde.',
  },
  game: {
    title: 'Ronda en Progreso',
    stop: '¡STOP!',
    stopping: 'Stopping...',
    submit: 'Enviar Respuestas',
    submitting: 'Enviando...',
    timeRemaining: 'Tiempo Restante',
    category: 'Categoría',
    yourAnswer: 'Tu respuesta',
    startingLetter: 'Letra Inicial',
    round: 'Ronda',
    of: 'de',
    score: 'Puntaje',
    maxScore: 'de 1000',
    loading: 'Cargando juego...',
    exit: 'Salir',
    answersSubmitted: '¡Respuestas enviadas!',
    enterAnswer: 'Ingresa tu respuesta',
    startRound: 'Start Round',
    startingRound: 'Starting...',
    roundStopped: 'Round stopped successfully',
    audioBlocked: 'Audio playback blocked by browser, but round stopped',
    scoreboard: 'Tabla de Puntuaciones',
  },
  tribunal: {
    title: 'Tribunal de Validación',
    subtitle: 'Vota por las palabras enviadas',
    approve: 'Aprobar',
    reject: 'Rechazar',
    waiting: 'Esperando votos...',
    submittedBy: 'Enviado por',
    continueToResults: 'Continuar a Resultados',
  },
  ranking: {
    title: 'Ranking Final',
    playAgain: 'Jugar de Nuevo',
    backToMenu: 'Volver al Menú',
    score: 'Puntaje',
    pts: 'pts',
    position: '#',
    winner: '¡Ganador!',
  },
  store: {
    title: 'Tienda',
    subtitle: 'Mejora tu experiencia de juego',
    purchase: 'Comprar',
    purchasing: 'Comprando...',
    backToMenu: 'Volver al Menú',
    premiumCategories: 'Paquete de Categorías Premium',
    premiumCategoriesDesc: 'Desbloquea categorías exclusivas venezolanas',
    avatarSkins: 'Paquete de Skins de Avatar',
    avatarSkinsDesc: 'Personaliza tu avatar con skins únicos',
    adRemoval: 'Eliminar Anuncios',
    adRemovalDesc: 'Disfruta de una experiencia sin anuncios para siempre',
  },
  payment: {
    success: '¡Pago Exitoso!',
    successDesc: 'Tu compra se ha completado exitosamente. ¡Disfruta tu nuevo contenido!',
    failure: 'Pago Fallido',
    failureDesc: 'Tu pago no pudo ser procesado. Por favor intenta de nuevo o contacta soporte.',
    backToMenu: 'Volver al Menú',
    tryAgain: 'Intentar de Nuevo',
  },
  admin: {
    title: 'Panel de Administración',
    subtitle: 'Administrar configuración y contenido del juego',
    loading: 'Cargando...',
    accessDenied: 'Acceso Denegado',
    accessDeniedDesc: 'No tienes permiso para acceder al panel de administración.',
    backToMenu: 'Volver al Menú',
    metrics: 'Métricas',
    dictionary: 'Diccionario',
    users: 'Usuarios',
    totalUsers: 'Total de Usuarios',
    totalRooms: 'Total de Salas',
    activeRooms: 'Salas Activas',
    bannedUsers: 'Usuarios Baneados',
    addWord: 'Agregar Palabra al Diccionario',
    wordLabel: 'Palabra',
    wordPlaceholder: 'Ingresa palabra para aprobar',
    addWordButton: 'Agregar Palabra',
    wordAdded: 'Palabra agregada al diccionario',
    banWord: 'Banear Palabra',
    banWordPlaceholder: 'Ingresa palabra para banear',
    banWordButton: 'Banear Palabra',
    wordBanned: 'Palabra baneada',
    userManagement: 'Gestión de Usuarios',
    userManagementDesc: 'Funciones de gestión de usuarios próximamente.',
    enterWord: 'Por favor ingresa una palabra',
  },
  auth: {
    signIn: 'Iniciar Sesión',
    signOut: 'Cerrar Sesión',
    signingIn: 'Iniciando sesión...',
    welcome: '¡Bienvenido a STOP Venezolano!',
    welcomeDesc: 'Antes de comenzar a jugar, por favor dinos tu nombre.',
    yourName: 'Tu Nombre',
    namePlaceholder: 'Ingresa tu nombre',
    letsPlay: '¡A Jugar!',
    settingUp: 'Configurando...',
    welcomeMessage: '¡Bienvenido a STOP Venezolano!',
    nameMinLength: 'El nombre debe tener al menos 2 caracteres',
    registrationFailed: 'Registro fallido',
  },
  errors: {
    connectionLost: '¡Conexión perdida! Reintentando...',
    unauthorized: 'Necesitas iniciar sesión para hacer eso',
    roomNotFound: 'Sala no encontrada',
    generic: 'Algo salió mal',
    purchaseFailed: 'Compra fallida',
    sessionMissingUrl: 'Sesión de Stripe sin URL',
    actorNotAvailable: 'Actor no disponible',
  },
  footer: {
    builtWith: 'Construido con',
    using: 'usando',
  },
  scoring: {
    validWord: '100 pts - Palabra válida única',
    repeatedWord: '50 pts - Palabra repetida',
    emptyWord: '0 pts - Vacío o incompleto',
    maxTotal: 'Máximo total: 1000 pts en 10 rondas',
  },
  pwa: {
    downloadApp: 'Descargar App',
    downloadDesc: 'Instala la app para jugar sin conexión',
    installButton: 'Instalar',
    installSuccess: '¡App instalada exitosamente!',
    manualInstallTitle: 'Cómo Instalar la App',
    manualInstallDesc: 'Sigue estos pasos para instalar la app en tu dispositivo:',
    iosStep1: 'Toca el botón de compartir en Safari',
    iosStep2: 'Desplázate y selecciona "Agregar a pantalla de inicio"',
    iosStep3: 'Toca "Agregar" para confirmar',
    androidStep1: 'Toca el menú (tres puntos) en Chrome',
    androidStep2: 'Selecciona "Instalar app" o "Agregar a pantalla de inicio"',
    androidStep3: 'Toca "Instalar" para confirmar',
  },
};
