/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Category = string;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface MonthlyScoreView {
    userId: UserId;
    wins: bigint;
    lastUpdated: Time;
    rounds: bigint;
    points: bigint;
}
export interface Score {
    player: UserId;
    points: bigint;
}
export type RoomId = bigint;
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface RoundPayload {
    isActive: boolean;
    totalRounds: bigint;
    letter: string;
    roundNumber: bigint;
}
export type UserId = Principal;
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface MatchProgress {
    lastRoundScores?: ScoringResult;
    currentRound: bigint;
    cumulativeScores: Array<Score>;
    isActive: boolean;
    currentLetter?: string;
    totalRounds: bigint;
    usedLetters: Array<string>;
}
export interface UserProfileView {
    id: UserId;
    name: string;
    banned: boolean;
    entitlements: Array<string>;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export type Submission = string;
export interface ScoringResult {
    maxPoints: bigint;
    valid: bigint;
    scores: Array<Score>;
    empty: bigint;
    repeats: bigint;
}
export interface RoomView {
    id: RoomId;
    categories: Array<Category>;
    active: boolean;
    host: UserId;
    mode: GameMode;
    players: Array<UserId>;
}
export enum GameMode {
    far = "far",
    near = "near"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addWord(word: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    banUser(userId: UserId): Promise<void>;
    banWord(word: string): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createRoom(mode: GameMode, categories: Array<Category>): Promise<RoomId>;
    getAllowedGameModes(): Promise<Array<GameMode>>;
    getAvailableRooms(): Promise<Array<RoomView>>;
    getCallerUserProfile(): Promise<UserProfileView | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCurrentMatchState(roomId: RoomId): Promise<MatchProgress>;
    getCurrentMonthLeaderboard(): Promise<Array<MonthlyScoreView>>;
    getCurrentTop1(): Promise<MonthlyScoreView | null>;
    getDictionaryEntry(word: string): Promise<boolean | null>;
    getMetrics(): Promise<{
        bannedUsers: bigint;
        activeRooms: bigint;
        totalUsers: bigint;
        totalRooms: bigint;
    }>;
    getMonthLeaderboard(month: string): Promise<Array<MonthlyScoreView>>;
    getMyMonthlyScore(month: string): Promise<MonthlyScoreView | null>;
    getMyRooms(): Promise<Array<RoomView>>;
    getRoom(roomId: RoomId): Promise<RoomView>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getUserProfile(user: Principal): Promise<UserProfileView | null>;
    getValidationResults(roomId: RoomId): Promise<Array<{
        submitter: UserId;
        word: string;
        category: Category;
        isValid: boolean;
    }>>;
    grantEntitlement(userId: UserId, entitlement: string): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    joinMatchmaking(): Promise<void>;
    joinRoom(roomId: RoomId): Promise<void>;
    leaveMatchmaking(): Promise<void>;
    leaveRoom(roomId: RoomId): Promise<void>;
    purchaseProduct(productId: string): Promise<string>;
    register(name: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfileView): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    startGame(roomId: RoomId): Promise<void>;
    startRound(roomId: RoomId): Promise<RoundPayload>;
    stopCurrentRound(roomId: RoomId): Promise<string>;
    submitWord(roomId: RoomId, category: Category, word: Submission): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    unbanUser(userId: UserId): Promise<void>;
    updateMonthlyScore(userId: UserId, pointsToAdd: bigint, isWin: boolean): Promise<void>;
}
import type { Category as _Category, GameMode as _GameMode, MatchProgress as _MatchProgress, MonthlyScoreView as _MonthlyScoreView, RoomId as _RoomId, RoomView as _RoomView, Score as _Score, ScoringResult as _ScoringResult, StripeSessionStatus as _StripeSessionStatus, UserId as _UserId, UserProfileView as _UserProfileView, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addWord(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addWord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWord(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async banUser(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.banUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.banUser(arg0);
            return result;
        }
    }
    async banWord(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.banWord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.banWord(arg0);
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createRoom(arg0: GameMode, arg1: Array<Category>): Promise<RoomId> {
        if (this.processError) {
            try {
                const result = await this.actor.createRoom(to_candid_GameMode_n3(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRoom(to_candid_GameMode_n3(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async getAllowedGameModes(): Promise<Array<GameMode>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllowedGameModes();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllowedGameModes();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableRooms(): Promise<Array<RoomView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableRooms();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableRooms();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfileView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentMatchState(arg0: RoomId): Promise<MatchProgress> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentMatchState(arg0);
                return from_candid_MatchProgress_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentMatchState(arg0);
            return from_candid_MatchProgress_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentMonthLeaderboard(): Promise<Array<MonthlyScoreView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentMonthLeaderboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentMonthLeaderboard();
            return result;
        }
    }
    async getCurrentTop1(): Promise<MonthlyScoreView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentTop1();
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentTop1();
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDictionaryEntry(arg0: string): Promise<boolean | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDictionaryEntry(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDictionaryEntry(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMetrics(): Promise<{
        bannedUsers: bigint;
        activeRooms: bigint;
        totalUsers: bigint;
        totalRooms: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getMetrics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMetrics();
            return result;
        }
    }
    async getMonthLeaderboard(arg0: string): Promise<Array<MonthlyScoreView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthLeaderboard(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthLeaderboard(arg0);
            return result;
        }
    }
    async getMyMonthlyScore(arg0: string): Promise<MonthlyScoreView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyMonthlyScore(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyMonthlyScore(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyRooms(): Promise<Array<RoomView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRooms();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRooms();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRoom(arg0: RoomId): Promise<RoomView> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoom(arg0);
                return from_candid_RoomView_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoom(arg0);
            return from_candid_RoomView_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfileView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getValidationResults(arg0: RoomId): Promise<Array<{
        submitter: UserId;
        word: string;
        category: Category;
        isValid: boolean;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.getValidationResults(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getValidationResults(arg0);
            return result;
        }
    }
    async grantEntitlement(arg0: UserId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.grantEntitlement(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.grantEntitlement(arg0, arg1);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async joinMatchmaking(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.joinMatchmaking();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinMatchmaking();
            return result;
        }
    }
    async joinRoom(arg0: RoomId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.joinRoom(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinRoom(arg0);
            return result;
        }
    }
    async leaveMatchmaking(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.leaveMatchmaking();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.leaveMatchmaking();
            return result;
        }
    }
    async leaveRoom(arg0: RoomId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.leaveRoom(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.leaveRoom(arg0);
            return result;
        }
    }
    async purchaseProduct(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.purchaseProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.purchaseProduct(arg0);
            return result;
        }
    }
    async register(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.register(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfileView): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async startGame(arg0: RoomId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.startGame(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startGame(arg0);
            return result;
        }
    }
    async startRound(arg0: RoomId): Promise<RoundPayload> {
        if (this.processError) {
            try {
                const result = await this.actor.startRound(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startRound(arg0);
            return result;
        }
    }
    async stopCurrentRound(arg0: RoomId): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.stopCurrentRound(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.stopCurrentRound(arg0);
            return result;
        }
    }
    async submitWord(arg0: RoomId, arg1: Category, arg2: Submission): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitWord(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitWord(arg0, arg1, arg2);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async unbanUser(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unbanUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unbanUser(arg0);
            return result;
        }
    }
    async updateMonthlyScore(arg0: UserId, arg1: bigint, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMonthlyScore(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMonthlyScore(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_GameMode_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameMode): GameMode {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_MatchProgress_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchProgress): MatchProgress {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_RoomView_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RoomView): RoomView {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfileView]): UserProfileView | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ScoringResult]): ScoringResult | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MonthlyScoreView]): MonthlyScoreView | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _RoomId;
    categories: Array<_Category>;
    active: boolean;
    host: _UserId;
    mode: _GameMode;
    players: Array<_UserId>;
}): {
    id: RoomId;
    categories: Array<Category>;
    active: boolean;
    host: UserId;
    mode: GameMode;
    players: Array<UserId>;
} {
    return {
        id: value.id,
        categories: value.categories,
        active: value.active,
        host: value.host,
        mode: from_candid_GameMode_n6(_uploadFile, _downloadFile, value.mode),
        players: value.players
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lastRoundScores: [] | [_ScoringResult];
    currentRound: bigint;
    cumulativeScores: Array<_Score>;
    isActive: boolean;
    currentLetter: [] | [string];
    totalRounds: bigint;
    usedLetters: Array<string>;
}): {
    lastRoundScores?: ScoringResult;
    currentRound: bigint;
    cumulativeScores: Array<Score>;
    isActive: boolean;
    currentLetter?: string;
    totalRounds: bigint;
    usedLetters: Array<string>;
} {
    return {
        lastRoundScores: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.lastRoundScores)),
        currentRound: value.currentRound,
        cumulativeScores: value.cumulativeScores,
        isActive: value.isActive,
        currentLetter: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.currentLetter)),
        totalRounds: value.totalRounds,
        usedLetters: value.usedLetters
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n22(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    far: null;
} | {
    near: null;
}): GameMode {
    return "far" in value ? GameMode.far : "near" in value ? GameMode.near : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GameMode>): Array<GameMode> {
    return value.map((x)=>from_candid_GameMode_n6(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RoomView>): Array<RoomView> {
    return value.map((x)=>from_candid_RoomView_n9(_uploadFile, _downloadFile, x));
}
function to_candid_GameMode_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameMode): _GameMode {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameMode): {
    far: null;
} | {
    near: null;
} {
    return value == GameMode.far ? {
        far: null
    } : value == GameMode.near ? {
        near: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
